### ISSUE TITLE
Responder clarification

### ISSUE THREAD

**Issue by fschwahn** [hilios/moulin_rouge#1]
Hi,
I'm wondering how the responder works on `update`-actions. A typical `respond_with` update action looks like this:

``` ruby
def update
  @player = Player.find(params[:id])
  @player.update_attributes(params[:player])
  respond_with(@player)
end
```

How can the authorization be enforced if the call to `update_attributes` happens before the `respond_with` call? 
Thanks for clarifying, I'm thinking of using your CanCanResponder-code with the `responders`-gem, but I was unsure how this point works.

Best regards,
Fabian

**Comment by hilios** [comment]
You don't need to authorize the user before the update. 

The default action when an exception is raised, is to execute rollback in the database, every rails action is enclosed by a SQL transaction.

 So you don need to worry about that, CanCan will raise an exception, and the sql will be rolled back.

**Comment by fschwahn** [comment]
Ah well, that makes sense... thank you!
